In [1]:
l = [23424, 27, 546, 214, -1234]

In [2]:
l

[23424, 27, 546, 214, -1234]

----

In [3]:
import numpy as np

In [5]:
a = np.array(l)

In [7]:
a #array is like vector in R
#we cannot have different types inside an array

array([23424,    27,   546,   214, -1234])

In [8]:
b = np.array([12,455,63.3, True, "abc"])

In [9]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [10]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [11]:
l.pop()

-1234

In [12]:
l

[23424, 27, 546, 214]

In [14]:
a.mean()

4595.4

--- SLICING ARRAYS ---

In [15]:
a

array([23424,    27,   546,   214, -1234])

In [16]:
a[2:]

array([  546,   214, -1234])

In [17]:
a[2:4]

array([546, 214])

In [18]:
b = a[2:4]

In [19]:
b

array([546, 214])

In [20]:
b[0]

546

In [22]:
b[:] = 111

In [23]:
b

array([111, 111])

In [24]:
a

array([23424,    27,   111,   111, -1234])

# SLICING ARRAYS DOESNT CREATE NEW ARRAY, IT JUST CREATE A VIEW OF ARRAYS 

# WATCH OUT FOR THAT

In [25]:
c = a.copy()

In [26]:
c[0]=0

In [27]:
c

array([    0,    27,   111,   111, -1234])

In [28]:
a

array([23424,    27,   111,   111, -1234])

# WE NEED TO CREATE COPY FIRST